### ISSUE TITLE
正規化について

### ISSUE THREAD

**Issue by kttaroha** [TakuyaInoue-github/introduction_of_baseinference#7]
# TL;DR
正規化の具体的なやり方がよくわからない

# ページ数（電子なら論理位置）
式（1.44）（1.4.5）

# 詳細
式（1.44）や（1.4.5）では離散分布に対する正規化を行っているが、連続分布の場合はどうやるのか？
と疑問に思ったが、単に積分するだけか

**Comment by TakuyaInoue-github** [comment]
素直に積分するだけで大丈夫だと思います。
